language: scala
sudo: required
dist: trusty

git:
  depth: false

matrix:
  include:
   - scala: 2.11.8
     env: SPARK=2.3.0
   - scala: 2.11.8
     env: SPARK=2.4.0
   - scala: 2.12.4
     env: SPARK=2.4.0

script:
  - curl -L -o ~/bin/mill https://github.com/lihaoyi/mill/releases/download/0.4.0/0.4.0 && chmod +x ~/bin/mill
  - export PATH=~/bin/mill:$PATH
  - mill "spark-constraints[$TRAVIS_SCALA_VERSION,$SPARK]"
cache:
  directories:
    - $HOME/.coursier
